export const LEGAL_VARIABLES = [
  "providerLegalName",
  "providerTaxId",
  "providerRegisteredAddress",
  "providerWebsite",
  "providerContractEmail",
  "providerPhone",
  "providerRepresentative",
  "providerSignatoryName",
  "providerSignatoryRole",
  "dataControllerLegalName",
  "dataControllerTaxId",
  "dataControllerAddress",
  "privacyContactEmail",
  "privacyPostalAddress",
  "privacyNoticeVersion",
  "privacyNoticeUrlOrAttachment",
  "agreementRetentionPeriod",
  "billingRetentionPeriod",
  "reportRetentionMonths",
  "videoRetentionDays",
  "accessLogRetentionMonths",
  "withdrawalDays",
  "withdrawalContact",
  "withdrawalRecipientLegalName",
  "withdrawalPostalAddress",
  "withdrawalEmail",
  "complaintsContact",
  "applicableLaw",
];

export const CLIENT_VARIABLES = [
  "customerFullName",
  "customerIdentityDocument",
  "customerNoticeAddress",
  "customerEmail",
  "customerPhone",
  "customerAuthorityBasis",
  "serviceAddress",
  "homeTypeAndSize",
];

export const CONTRACT_VARIABLES = [
  ...CLIENT_VARIABLES,
  "signedAtDate",
  "signedAtPlace",
  "evidenceChoiceInitials",
  "providerSignatureDate",
  "customerSignatureDate",
  "providerAnnexSignatureDate",
  "customerAnnexSignatureDate",
  "planNameOrQuoteId",
  "visitsPerCalendarMonth",
  "serviceStartDate",
  "serviceTermAndBillingMode",
  "finalPriceAndVat",
  "billingScheduleAndMethod",
  "visitWindowAndServiceHours",
  "reportDeliveryTermAndChannel",
  "homeManagerNameAndContact",
  "authorizedContacts",
  "includedAreas",
  "excludedAreas",
  "authorizedEquipment",
  "authorizedShutters",
  "exitProfile",
  "otherAuthorizedSimpleAction",
  "explicitlyUnauthorizedActions",
  "accessMethodCategory",
  "keyCustodyYesNo",
  "keyReceiptReference",
  "authorizedAccessRolesOrPeople",
  "failedAccessRule",
  "reschedulingRule",
  "evidenceModeVideoOrPhotos",
  "recordingFailureContingency",
  "reportRecipients",
  "secureDeliveryChannel",
  "customEmergencySpendLimit",
  "spendAuthorizers",
  "writtenAuthorizationChannel",
  "incidentContactOrder",
  "terminationNoticeAndMethod",
  "unusedVisitsRule",
  "annualPlanTerminationTermsOrNa",
  "accessReturnMethod",
];

export const RECORD_SCHEMAS = {
  legalIdentity: {
    topLevel: ["status", "legalReviewApproved", "fictitious", "variables"],
    required: ["status", "legalReviewApproved", "variables"],
    variables: LEGAL_VARIABLES,
  },
  contract: {
    topLevel: [
      "status",
      "fictitious",
      "contractId",
      "templateVersion",
      "variables",
      "choices",
    ],
    required: ["status", "contractId", "templateVersion", "variables", "choices"],
    variables: CONTRACT_VARIABLES,
  },
};

export function selectVariables(source, names) {
  return Object.fromEntries(names.map((name) => [name, source[name]]));
}
