# Upgrade the $TERM variable
set -g default-terminal "screen-256color"

# Tell tmux that the outside terminal supports RGB (TrueColor)
# This part is crucial for modern color schemes
set -as terminal-features ",xterm-256color:RGB"

set -g default-command "${SHELL}"
set -g mouse off
set -g history-limit 50000
setw -g mode-keys emacs

bind-key -r C-n resize-pane -U
bind-key -r C-m resize-pane -D
