#!/usr/bin/env zsh

source /opt/powerlevel10k/powerlevel10k.zsh-theme

export LANG="en_US.UTF-8"
export LC_COLLATE="C"
export EDITOR=vim
export PGCLIENTENCODING="utf8"

export _JAVA_AWT_WM_NONREPARENTING=1

bindkey -e
bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char
bindkey    '^R'             history-incremental-search-backward

#autoload -U promptinit
#promptinit
#prompt zefram

#------------------------------
## Comp stuff
##------------------------------

zmodload zsh/complist
autoload -Uz compinit
compinit

zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*:pacman:*' force-list always
zstyle ':completion:*:*:pacman:*' menu yes select

#------------------------------
# Alias stuff
#------------------------------
alias ls="ls --color -F"
alias ll="ls --color -lh"
alias 'lsd'='ls -d *(/)'
alias 'lsf'='ls -h *(.)'
alias 'rm'='rm -r'
alias 'cp'='cp -r'
alias 'l'='ls --color -GFlh'

#-----------------
# Options
#-----------------

setopt AUTO_CD               # implicate cd for non-commands
setopt CORRECT_ALL            # correct spelling
setopt COMPLETE_IN_WORD    # complete commands anywhere in the word
setopt NOTIFY              # Notify when jobs finish
setopt BASH_AUTO_LIST      # Autolist options on repeition of ambiguous args
setopt MULTIOS             # Allow Multiple pipes
setopt EXTENDED_GLOB
setopt NOBEEP
setopt INC_APPEND_HISTORY

export HISTSIZE=5000
export SAVEHIST=5000
export HISTFILE=~/.zhistory

## OTHER OPTS
setopt hist_ignore_all_dups
setopt hist_ignore_space

bindkey -e

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
